title: Ibrahim Rameez M K
logo: https://github.com/IbrahimRameez/Rameez_portfolio/blob/583d7703657e48f42ebe7a343c6b8162e137c487/WhatsApp%20Image%202025-11-26%20at%206.50.10%20PM.jpeg
theme: jekyll-remote-theme
